name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:
    branches: [main]
jobs:
  Sync-Database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PNPM  
        run: npm install --global pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Create prisma client
        run: pnpm exec prisma generate
      - name: Sync database with schema
        run: pnpm exec prisma migrate deploy
  Deploy-App:
    runs-on: ubuntu-latest
    needs: [Sync-Database]
    steps:
      - uses: actions/checkout@v2
      - name: Install PNPM
        run: npm install --global pnpm
      - name: PNPM Setup
        run: pnpm setup
      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=deploy --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
